version: 2.1
jobs:
  test:
    working_directory: ~/Devops_Projects/Docker/docker-circleci-pipeline
    docker:
      - image: python:3.9
    steps:
      - checkout:
          path: ~/Devops_Projects
      - run: pip3 install -r requirements.txt
      - run: pytest
  build-and-push:
    working_directory: ~/Devops_Projects/Docker/docker-circleci-pipeline
    docker:
      - image: docker:latest
    steps:
      - checkout:
          path: ~/Devops_Projects
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: sudo docker build -t wisdom209/demo-flask-app .
      - run: sudo  docker push wisdom209/demo-flask-app
workflows:
  test-and-build:
    jobs:
      - test
      - build-and-push
