version: 2.1
jobs:
  build:
    working_directory: ~/Devops_Projects/Docker/docker-circleci-pipeline
    docker:
      - image: docker:latest
    steps:
      - checkout:
          path: ~/Devops_Projects
      - run: docker build -t demo-cicd-app .
      - run: docker run -dit --name demo-cicd-app -p 8080:80 demo-cicd-app
